#ifndef RACE_CONFIG_H
#define RACE_CONFIG_H

#define RACE_SCREEN_WIDTH      240
#define RACE_SCREEN_HEIGHT     240

#define RACE_PLAYER_START_X 120.0f
#define RACE_PLAYER_START_Y 180.0f
#define RACE_PLAYER_WIDTH   12
#define RACE_PLAYER_HEIGHT  18
#define RACE_PLAYER_SPEED   2.0f

#define RACE_TRACK_WIDTH 90U
#define RACE_TRACK_TOP_Y 20U
#define RACE_TRACK_BOTTOM_Y 225U
#define RACE_TRACK_LANE_GAP 18U
#define RACE_TRACK_SCROLL_STEP 2U
#define RACE_TRACK_EDGE_PADDING 2U

#endif 