#ifndef RACE_CONFIG_H
#define RACE_CONFIG_H

// SCREEN / TILE / WORLD SETUP

// The LCD visible area is still 240x240 pixels.
#define RACE_SCREEN_WIDTH 240U
#define RACE_SCREEN_HEIGHT 240U

// We are using 8x8 tiles.
#define RACE_TILE_SIZE 8U

// Larger world map.
// 90 tiles wide  = 720 px
// 60 tiles high  = 480 px
#define RACE_WORLD_TILES_X 90U
#define RACE_WORLD_TILES_Y 60U

// Visible camera area.
// 30 tiles x 30 tiles = 240x240 px.
#define RACE_VIEW_TILES_X 30U
#define RACE_VIEW_TILES_Y 30U

#define RACE_WORLD_WIDTH_PX (RACE_WORLD_TILES_X * RACE_TILE_SIZE)
#define RACE_WORLD_HEIGHT_PX (RACE_WORLD_TILES_Y * RACE_TILE_SIZE)

#define RACE_VIEW_WIDTH_PX (RACE_VIEW_TILES_X * RACE_TILE_SIZE)
#define RACE_VIEW_HEIGHT_PX (RACE_VIEW_TILES_Y * RACE_TILE_SIZE)

// PLAYER START

#define RACE_PLAYER_START_X 92.0f
#define RACE_PLAYER_START_Y 388.0f

#define RACE_PLAYER_WIDTH 10U
#define RACE_PLAYER_HEIGHT 14U

// SMOOTH ARCADE HANDLING

// Lower response = smoother.
// Higher response = sharper.
#define RACE_CAR_ACCELERATION_RESPONSE 0.16f
#define RACE_CAR_DECELERATION_RESPONSE 0.11f
#define RACE_CAR_DRAG_MULTIPLIER 0.93f
#define RACE_CAR_MAX_SPEED 3.15f

#define RACE_CAR_WALL_BOUNCE_MULTIPLIER 0.10f

// CAMERA

#define RACE_CAMERA_TARGET_X 120.0f
#define RACE_CAMERA_TARGET_Y 120.0f
#define RACE_CAMERA_SMOOTHING 0.095f

// RACE PROGRESSION

#define RACE_TOTAL_LAPS 3U
#define RACE_CHECKPOINT_COUNT 3U

// LCD PALETTE COLOUR INDICES

#define RACE_COLOUR_BLACK 0U
#define RACE_COLOUR_WHITE 1U
#define RACE_COLOUR_RED 2U
#define RACE_COLOUR_GREEN 3U
#define RACE_COLOUR_BLUE 4U
#define RACE_COLOUR_ORANGE 5U
#define RACE_COLOUR_YELLOW 6U
#define RACE_COLOUR_BROWN 12U
#define RACE_COLOUR_GREY 13U
#define RACE_COLOUR_CYAN 14U

// Track/scenery colours.
#define RACE_COLOUR_SAND RACE_COLOUR_ORANGE
#define RACE_COLOUR_GRASS RACE_COLOUR_GREEN
#define RACE_COLOUR_ROAD RACE_COLOUR_GREY
#define RACE_COLOUR_ROAD_DARK RACE_COLOUR_BLACK
#define RACE_COLOUR_WALL RACE_COLOUR_WHITE
#define RACE_COLOUR_CURB_RED RACE_COLOUR_RED
#define RACE_COLOUR_CURB_WHITE RACE_COLOUR_WHITE
#define RACE_COLOUR_TYRE RACE_COLOUR_BLACK
#define RACE_COLOUR_BARRIER RACE_COLOUR_WHITE

// Race markers.
#define RACE_COLOUR_START RACE_COLOUR_YELLOW
#define RACE_COLOUR_CHECKPOINT RACE_COLOUR_CYAN
#define RACE_COLOUR_JOKER RACE_COLOUR_RED

// Player.
#define RACE_COLOUR_PLAYER RACE_COLOUR_BLUE
#define RACE_COLOUR_PLAYER_NOSE RACE_COLOUR_WHITE

// HUD.
#define RACE_COLOUR_HUD_BG RACE_COLOUR_BLACK
#define RACE_COLOUR_HUD_TEXT RACE_COLOUR_WHITE
#define RACE_HUD_HEIGHT 24U

// Collision compatibility.
#define RACE_COLLISION_EDGE_SPEED_MULTIPLIER 0.35f
#define RACE_COLLISION_EDGE_HEADING_MULTIPLIER 0.50f
#define RACE_CRASH_SPEED_THRESHOLD 99.0f

#define RACE_MAX_DAMAGE 100U
#define RACE_CURB_DAMAGE_AMOUNT 4U
#define RACE_CURB_DAMAGE_COOLDOWN_FRAMES 14U
#define RACE_CURB_DAMAGE_SPEED_THRESHOLD 0.65f


#endif